apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextd.fullname" . }}
  labels:
    {{- include "nextd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextd.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nextd.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nextd
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nextd.fullname" . }}-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "nextd.secretName" .) .Values.postgresql.existingSecret }}
                  key: {{ .Values.postgresql.passwordKey }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "nextd.secretName" .) .Values.jwt.existingSecret }}
                  key: {{ .Values.jwt.secretKey }}
            - name: AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "nextd.secretName" .) .Values.ai.existingSecret }}
                  key: {{ .Values.ai.apiKeyKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
