{{- if or (not .Values.postgresql.existingSecret) (not .Values.jwt.existingSecret) (not .Values.ai.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextd.secretName" . }}
  labels:
    {{- include "nextd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.existingSecret }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- end }}
  {{- if not .Values.jwt.existingSecret }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  {{- end }}
  {{- if not .Values.ai.existingSecret }}
  AI_API_KEY: {{ .Values.ai.apiKey | quote }}
  {{- end }}
{{- end }}
